import { AlertTriangle, ArrowLeft, CirclePower, Network, Route, ShieldCheck } from "lucide-react";
import type { TunStatusSnapshot } from "../api/mihomo";
import type { Page } from "../components/Sidebar";

export function TunPage({ profileId, coreRunning, systemProxyEnabled, snapshot, loading, error, onRequestTransition, onNavigate }: {
  profileId: string | null;
  coreRunning: boolean;
  systemProxyEnabled: boolean;
  snapshot: TunStatusSnapshot | null;
  loading: boolean;
  error: string | null;
  onRequestTransition: () => void;
  onNavigate: (page: Page) => void;
}) {
  const status = snapshot?.status ?? "disabled";
  const transitioning = status === "starting" || status === "stopping";
  const external = Boolean(snapshot?.owner === "external" || snapshot?.actualState === "externalTun" || snapshot?.externalDetected);
  const owned = Boolean(snapshot?.owner === "mioproxy" && snapshot?.actualState === "mioproxyTun" && status === "running");
  const willDisable = !external && Boolean(owned || snapshot?.desiredEnabled);
  const blockedForEnable = !coreRunning || !profileId || external;

  return (
    <section className="page-stack tun-page">
      <header className="page-header compact-header">
        <div><button className="back-link" type="button" onClick={() => onNavigate("settings")}><ArrowLeft size={14} />Settings</button><h1>TUN</h1><p>Inspect and control the shared MioProxy TUN runtime snapshot.</p></div>
        <button className={willDisable ? "danger-button" : "primary-button"} type="button" onClick={onRequestTransition} disabled={loading || !snapshot || transitioning || (!willDisable && blockedForEnable)} aria-pressed={Boolean(snapshot?.desiredEnabled)}><CirclePower size={15} />{loading || transitioning ? "Working…" : external ? "External TUN" : willDisable ? "Turn off" : status === "error" ? "Retry" : "Turn on"}</button>
      </header>
      {error && <div className="info-bar error" role="alert"><AlertTriangle size={16} /><span>{error}</span></div>}
      {snapshot?.message && <div className={status === "error" ? "info-bar error" : "info-bar success"}><ShieldCheck size={16} /><span>{snapshot.message}</span></div>}

      <section className="surface-panel tun-runtime-panel">
        <div className="section-title-row"><div><h2>Runtime projection</h2><p>{external ? "External ownership detected; MioProxy will not take over from this control." : "Derived from the shared TUN status contract."}</p></div><span className={`state-value tone-${status === "error" ? "error" : external || transitioning ? "warning" : owned ? "success" : "muted"}`}><span className="state-dot" />{external ? "External" : transitioning ? "Transitioning" : owned ? "On" : status === "error" ? "Error" : snapshot ? "Off" : "Checking"}</span></div>
        <dl className="form-details">
          <div><dt>Owner</dt><dd>{snapshot?.owner ?? "—"}</dd></div>
          <div><dt>Actual state</dt><dd>{snapshot?.actualState ?? "—"}</dd></div>
          <div><dt>Desired</dt><dd>{snapshot ? snapshot.desiredEnabled ? "Enabled" : "Disabled" : "—"}</dd></div>
          <div><dt>Core</dt><dd>{coreRunning ? "Ready" : "Not ready"}</dd></div>
          <div><dt>System Proxy</dt><dd>{systemProxyEnabled ? "On" : "Off"}</dd></div>
          <div><dt>Profile for TUN session</dt><dd>{snapshot?.profileId ?? profileId ?? "—"}</dd></div>
        </dl>
      </section>

      {(!coreRunning || !profileId || external) && <div className="surface-panel prerequisite-row"><AlertTriangle size={16} /><div><strong>{external ? "External TUN is active" : "Enable prerequisites"}</strong><span>{external ? "Disable the external TUN in its owning application before asking MioProxy to enable its own TUN." : !coreRunning ? "Wait for Core to become Ready." : "Select a downloaded Profile first."}</span></div></div>}
      <section className="surface-panel tun-contract-note"><Route size={16} /><div><strong>Configuration details</strong><span>Auto-route, interface detection and DNS hijack values are generated by the backend. They are intentionally not shown as enabled unless a read contract exposes them.</span></div><Network size={16} /></section>
    </section>
  );
}
